import 'dart:async';

import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

// Import all entities
import 'package:kalimati/features/dashboard/domain/entities/sentence.dart';
import 'package:kalimati/features/dashboard/domain/entities/word.dart';
import 'package:kalimati/features/dashboard/domain/entities/definition.dart';
import 'package:kalimati/features/dashboard/domain/entities/learning_package.dart';
import 'package:kalimati/features/dashboard/domain/entities/resource.dart';

// Import all DAOs
import 'package:kalimati/core/data/database/daos/definition_dao.dart';
import 'package:kalimati/core/data/database/daos/package_dao.dart';
import 'package:kalimati/core/data/database/daos/resource_dao.dart';
import 'package:kalimati/core/data/database/daos/sentence_dao.dart';
import 'package:kalimati/core/data/database/daos/word_dao.dart';

// This will be generated by Floor
part 'app_database.g.dart';

@Database(
  version: 1,
  entities: [
    // User,
    LearningPackage,
    Word,
    Definition,
    Sentence,
    Resource,
  ],
)
abstract class AppDatabase extends FloorDatabase {
  // Get all DAOs - these will be implemented in the generated file

  //UserDao get userDao;

  PackageDao get packageDao;

  WordDao get wordDao;

  DefinitionDao get definitionDao;

  SentenceDao get sentenceDao;

  ResourceDao get resourceDao;
}
